# os.system("xclip -o")
    # clip = subprocess.check_output('xclip -o', shell=True)
    # clip = subprocess.123check_output(["xclip -o"])
    #new_output = '%s\b test'%(clip)
    #print(new_output[2:])
    #root.bind("<Control-Key-2>",paste(new_output[2:]))
    # root.bind("<Control-Key-2>",paste('abc'))
    # print(pyautogui.position())
    # pyautogui.click(x=1543, y=208)
    # pyautogui.typewrite('Hello world!', interval=0.25)
    #  # print(pyautogui.position())    # root.bind("<Control-slash>",func)
    #   
